- name: Install Mysql
  ansible.builtin.command: dnf install mysql-server -y

- name: enable Mysql
  ansible.bulitin.service:
    name: mysqld
    state: started
    enabled: yes

- name: install boto3 and botocore
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
    - boto3
    - botocore

- name: setp root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASSWORD }}
