- name: Create App directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Create system User for {{ component }}
  ansible.builtin.user:
    name: roboshop
    comment: "Roboshop user"
    shell: /sbin/nologin
    system: true
    home: /app

- name: Download Config file
  ansible.builtin.get_url:
    url: "https://roboshop-artifacts.s3.amazonaws.com/{{component}}-v3.zip"
    dest: "/tmp/{{ component }}.zip"

- name: Unzip the {{ component }} data content
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes
